### ISSUE TITLE
[KeyPoints] - extend `from_mediapipe` with Google MediaPipe FaceMesh

### ISSUE THREAD

**Issue by LinasKo** [roboflow/supervision#1274]
# Description

Much like #1174 and #1232 adding pose landmark support, we'd also like to add face detection support to the `from_mediapipe` method.

* Add `Skeleton.FACEMESH_TESSELETION` of size `468` to the [Skeleton](https://github.com/roboflow/supervision/blob/447ef41fc45353130ec4dccdc7eeaf68b622fb7e/supervision/keypoint/skeletons.py#L7) enum.
  * The nodes can be found here: https://github.com/google-ai-edge/mediapipe/blob/8cb99f934073572ce73912bb402a94f1875e420a/mediapipe/python/solutions/face_mesh_connections.py#L74
  * Docs can be found here: https://github.com/google-ai-edge/mediapipe/blob/master/docs/solutions/face_mesh.md
* Add the code to the `from_mediapipe` function in [`KeyPoints`](https://github.com/roboflow/supervision/blob/447ef41fc45353130ec4dccdc7eeaf68b622fb7e/supervision/keypoint/core.py#L16) object that is introduced in #1232.
* We'd like to support responses from both legacy and modern way to call the face mesher - see links below.

![facemesh](https://github.com/roboflow/supervision/assets/6500785/59433e66-74e0-448c-b902-4f19947d379e)

# Links:
- Google Mediapipe repository: https://github.com/google/mediapipe
- Google Mediapipe face landmarker: https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker
  - Python Guide (Modern): https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker/python
  - Legacy: https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/face_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Face_Landmarker.ipynb
- Skeletons: https://github.com/google-ai-edge/mediapipe/blob/8cb99f934073572ce73912bb402a94f1875e420a/mediapipe/python/solutions/face_mesh_connections.py#L74

# Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by LinasKo** [comment]
Hey @David-rn,

I saw your comment regarding the lazy loader / high memory usage issue. I need to scope out that one first, but if you're keen to contribute and enjoyed the work on MediaPipe, this one is up for grabs 😉

**Comment by onuralpszr** [comment]
@LinasKo  if not I worked face mesh before  so I really want to be involved too

**Comment by LinasKo** [comment]
Hi @onuralpszr,

Sure, we can reserve it for you - I recall you mentioning it before 🙂 

However, we can afford to a wait a little bit, so I'd prefer to close the sinks and maybe the water meter cookboks first (I have some feedback to send about the latter).

**Comment by LinasKo** [comment]
Hey @David-rn,

I appreciate there's been some delay. Would you be interested in doing this?

We've decided with @onuralpszr to open this to the community, as he's already overseeing many other important features 🙂

**Comment by David-rn** [comment]
Hey! 👋

 Sure, I'd like to participate! I'll give a look during these days.

**Comment by LinasKo** [comment]
Thank you @David-rn! Assigning it to you.

**Comment by David-rn** [comment]
Hi @LinasKo! I came across with a doubt and I wanted to confirm with you the correct implementation. 

The [modern way](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker/python#create_the_task) of FaceMesh return 478 landmarks in which the last 10 correspond to the irises. However, in the [legacy way](https://github.com/google-ai-edge/mediapipe/blob/master/docs/solutions/face_mesh.md) it will output 468 or 478 landmarks depending on whether the `refine_landmarks` option is set to False or True as shown [here](https://github.com/google-ai-edge/mediapipe/issues/3006). 

On the other hand, the `EdgeAnnotator` class uses the SKELETONS_BY_VERTEX_COUNT variable to draw the vertices. Since this variable selects the skeleton according to the number of unique vertices, should supervision provide two type of Skeletons (468 & 478 vertices, which will create an enormous list) or should we cast the mediapipe result into the 468 mentioned in the issue description and use only the FACEMESH_TESSELATION?

PS: Mediapipe uses a different [variable name](https://github.com/google-ai-edge/mediapipe/blob/8cb99f934073572ce73912bb402a94f1875e420a/mediapipe/python/solutions/face_mesh_connections.py#L72) for handling the irises (the landmark count goes from 469 to 477).

**Comment by LinasKo** [comment]
Let's add 2 skeletons. I can see us having `FACEMESH_TESSELATION_NO_IRIS` and `FACEMESH_TESSELATION` if it's what mediapipe can return.

Enums can refer to their prior value, so you can compose the skeletons if you wish, so only`FACEMESH_TESSELATION_NO_IRIS` entry would be enormous.

```python
from enum import Enum
from typing import Dict, List, Tuple

Edges = List[Tuple[int, int]]


class TestEnum(Enum):
    ONE = [
        (1, 2),
        (1, 3),
        (2, 3),
        (2, 4),
    ]

    TWO = [
        (1, 2),
        (1, 5),
        (2, 3),
    ]

    THREE = ONE + TWO

print(TestEnum.ONE.value)
print(TestEnum.TWO.value)
print(TestEnum.THREE.value)
```

Hope that answers your questions!
