### ISSUE TITLE
tracker_id gives new id when losing the object

### ISSUE THREAD

**Issue by litaldavar** [roboflow/supervision#132]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I'm using supervision 0.3.0
each time my object is lost for a while and comes back, it is with a new tracker id 
Please help,

attaching a clip for you to see

https://github.com/roboflow/supervision/assets/4908360/2e480629-a821-4618-9354-cd756e6d44e8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @litaldavar 👋🏻! Unfortunately, this problem is unrelated to `supervision`. For this reason, I am closing the issue.

As I don't want to leave you without help, here are some tips.

- Train your detector so that it does not lose detection. It looks like your training set was missing images where the beetle was very close to the edge, and consequently, your model is now having trouble detecting it. Add such images along with annotations and train the model once again.
- I assume you are using ByteTrack. It is a tracker based on the IoU. It requires the bounding box on consecutive frames to overlap. This is the only criterion that is taken into account. If you are not able to guarantee this, choose another tracker - one that takes into account the unique features of the object, such as DeepSort.

**Comment by litaldavar** [comment]
ByteTrack did not lose tracker id, but it is impossible to work with. I changed to native tracking with ultralytics and supervision only when the problem appeared. Do I need to see if ultralytics can fix this?

**Comment by SkalskiP** [comment]
> it is impossible to work with

Could you elaborate?

> do I need to see if ultralytics can fix this?

To my knowledge ultralytics is also using ByteTrack.
