### ISSUE TITLE
Clarification of obb behaviour with InferenceSlicer

### ISSUE THREAD

**Issue by robmarkcole** [roboflow/supervision#1394]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Based on [reviewing source code](https://github.com/roboflow/supervision/blob/a8d91b0ae5a17ccf93aa83d5866cf5daa511d7a3/supervision/detection/core.py#L258), I understand that with an obb model, the regular box enclosing the obb box is used with SAHI. As a result, merged regular boxes, and not obb boxes are returned. I wanted to confirm this, and suggest a note is added in the docs. 

I also want to know if this could be responsible for the odd predictions below - perhaps the enclosing boxes are not merged correctly:

![image](https://github.com/user-attachments/assets/7890dfe8-b8c1-42be-b98e-6b1c54bdb075)

**Comment by SkalskiP** [comment]
Hi, @robmarkcole 👋🏻 Lots to unpack here.

- OBB support in `InferenceSlicer` has not been officially released yet, but we're working on it. (We should perhaps explicitly state that only object detection and instance segmentation are currently supported.)
- A test version of OBB in `InferenceSlicer` is available in the `develop` branch. You can read more about it [here](https://github.com/roboflow/supervision/issues/1339) and [here](https://github.com/roboflow/supervision/pull/1350). To use it, you would need to install supervision like this: `pip install git+https://github.com/roboflow/supervision.git`.
- If you want to plot OBB, use [`OrientedBoxAnnotator`](https://supervision.roboflow.com/develop/detection/annotators/#supervision.annotators.core.OrientedBoxAnnotator) instead of `BoundingBoxAnnotator` (deprecated) or [`BoxAnnotator`](https://supervision.roboflow.com/develop/detection/annotators/#supervision.annotators.core.BoxAnnotator).
- Regarding the quality of the result you received, it might be related to the second [issue](https://github.com/roboflow/supervision/issues/1395) you opened - incorrect channel order. What `slice_wh` value are you using? The default is `(320, 320)`, I'd try to increase it to `(640, 640)`.

**Comment by robmarkcole** [comment]
Thanks @SkalskiP these results are much better!

<img width="461" alt="image" src="https://github.com/user-attachments/assets/d639717c-6342-4d92-8ba7-b635ef9aa858">

```python
image_path = "my.png"
image = np.array(Image.open(image_path))

def callback(image_slice: np.ndarray) -> sv.Detections:
    result = model(image_slice)[0]
    return sv.Detections.from_ultralytics(result)

slicer = sv.InferenceSlicer(callback = callback, slice_wh=(768, 768))
detections = slicer(image)
detections = detections[detections.class_id == 1] # ships id in DOTA

oriented_box_annotator = sv.OrientedBoxAnnotator()
label_annotator = sv.LabelAnnotator()

annotated_image = oriented_box_annotator.annotate(scene=image, detections=detections)
annotated_image = label_annotator.annotate(scene=annotated_image, detections=detections)
```

**Comment by SkalskiP** [comment]
@robmarkcole that is true; this looks a lot better! There is still room for improvement. Especially where it comes to post-processing and merging double detections. We don't have that component yet for OBB. 

Can I close the issue?

**Comment by 050603** [comment]
![image](https://github.com/user-attachments/assets/ebfc55dd-d276-4354-a189-bebbff8adb97)
  `import cv2
import numpy as np
import supervision as sv
from ultralytics import YOLO
from PIL import Image

model = YOLO("/root/autodl-tmp/code/ultralytics/runs/obb/train/weights/best.pt")

image_path = "/root/autodl-tmp/DOTA/images/test/P1068.png"
image = np.array(Image.open(image_path))

def callback(image_slice: np.ndarray) -> sv.Detections:
    result = model(image_slice)[0]
    return sv.Detections.from_ultralytics(result)

slicer = sv.InferenceSlicer(callback = callback)
# slicer = sv.InferenceSlicer(callback = callback, slice_wh=(768, 768))
detections = slicer(image)

oriented_box_annotator = sv.OrientedBoxAnnotator()
# oriented_box_annotator = sv.BoundingBoxAnnotator()
label_annotator = sv.LabelAnnotator()

annotated_image = oriented_box_annotator.annotate(scene=image, detections=detections)
annotated_image = label_annotator.annotate(scene=annotated_image, detections=detections)

annotated_pil_image = Image.fromarray(annotated_image)
annotated_pil_image.show()`

@SkalskiP     Why doesn't the target box display at the correct scale when drawing with OrientedBoxAnnotator?

**Comment by LinasKo** [comment]
I believe we have a fix in the `develop` branch.

Did you try this?
`pip install git+https://github.com/roboflow/supervision.git@develop`

**Comment by 050603** [comment]
> I believe we have a fix in the `develop` branch.
> 
> Did you try this? `pip install git+https://github.com/roboflow/supervision.git@develop`

@LinasKo Yes, that's how I do it.

**Comment by 050603** [comment]
@LinasKo I checked the saved CSV file and found that the coordinates were all relative to the pixel position of the slice (up to 640), without considering the position of the slice itself.
![image](https://github.com/user-attachments/assets/a8a433e0-fc2e-4c6b-8851-521be1282585)

**Comment by SkalskiP** [comment]
Hi @050603 👋🏻 is there any chance you could provide us with your model and image?
