### ISSUE TITLE
New ByteTrack 

### ISSUE THREAD

**Issue by litaldavar** [roboflow/supervision#186]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi, It looks like ByteTrack changed their installation. I was wondering if you could make a new video about tracking and counting with 
ByteTrack and supervision (YOLOv8) 
Everything in ByteTrack changed.
I wanted to use the Ultralytics tracking, but they did not implement the ReID, and I keep losing my object when it goes behind other objects.
It will be very helpful to keep using supervision in my project
Thank you

**Comment by hardikdava** [comment]
Hi @litaldavar, thanks for raising the issue. We are not on team of `Ultralytics`. We can not help you with this issue since it is related to `Ultralytics` package. `Supervision` only provides intermediate tools to build your application efficiently. Though you can refer #126 which has the same discussion on `yolov8`. It has code snippet which might be interested for you. `Supervision` does not provide any tracking ReID feature. so we can not help you in this case. Feel free to raise issue regarding `supervision`.
