### ISSUE TITLE
large dataset processing 

### ISSUE THREAD

**Issue by Alaaeldinn** [roboflow/supervision#876]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

In the file  within the function 'save_dataset_images()', there is an inefficient memory usage problem. The function currently uses 'cv2.imwrite' to write the images in the new dataset. However, this approach is memory-intensive cause it stores the entire images from 'Dict[str, np.ndarray]', resulting in significant memory consumption that can potentially lead to system crashes. to resolve just move the whole image without storing it 

   

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
Hello @Alaaeldinn 👋 

This is a known bug and we have a PR https://github.com/roboflow/supervision/pull/353 to for fix and we will take a look. I am closing this report because we already one in here (https://github.com/roboflow/supervision/issues/316) Please follow existing PR/Issue as well. 

Thank you.
